apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-argo
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/omriwa/helm.git
    targetRevision: HEAD
    path: webapp/webapp-helm-charts
  destination:
    server: https://kubernetes.default.svc
    namespace: development-webapp

  syncPolicy:
    syncOptions:
    - CreateNameSpace=true
    
    automated:
     selfHeal: true
     prune: true